name: Deploy Project
on: push
# jobs will run in parallel
jobs:
  #job 1
  test:
    # with ubuntu-latest machine
    # nodejs v16 is already installed
    # but we want v18
    runs-on: ubuntu-latest
    steps:
      # download code
      - name: Get code from repository
        uses: actions/checkout@v2
      # install NodeJs
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # install NodeJs
      - name: Install dependencies
        # or npm install
        # ci makes sure to use dependency versions locked in package.json file
        run: npm ci
      # run tests
      - name: Run test
        run: npm test
  #job 1
  deploy:
    # runner machine
    runs-on: ubuntu-latest
    steps:
      # download code
      - name: Get code from repository
        uses: actions/checkout@v2
      # install NodeJs
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # install NodeJs
      - name: Install dependencies
        # or npm install
        # ci makes sure to use dependency versions locked in package.json file
        run: npm ci
      # build project as code you write during dev is not same as code users will get
      - name: Build project
        # will target build script in package.json file
        run: npm run build
      # upload to web host that serves website
      - name: Deploy
        run: echo "Deploying..."
