name: Handle issues
on: issues
# runs when new issues are created in our repository
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
