name: Test Project
on: push
jobs:
  test:
    # with ubuntu-latest machine
    # nodejs v16 is already installed
    # but we want v18
    runs-on: ubuntu-latest
    steps:
      # download code
      - name: Get code from repository
        uses: actions/checkout@v2
      # install NodeJs
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # install NodeJs
      - name: Install dependencies
        # or npm install
        # ci makes sure to use dependency versions locked in package.json file
        run: npm ci
      # run tests
      - name: Run test
        run: npm test
